#include "soft_rig.hpp"
#include <iostream>
#include <stdexcept>
using namespace boltyard;
void run(SoftRig&r,float seconds,float t=0,bool brake=false,float dt=1.f/120){for(int i=0;i<int(seconds/dt+.5f);++i)r.step(dt,t,0,brake);}
void check(bool b,const char*m){if(!b)throw std::runtime_error(m);}
void healthy(const SoftRig&r){check(r.safety_clamp_count()==0&&r.rejected_state_count()==0&&r.damage()<.01f,"unstable or damaged");}
Config crawler(){Config c;c.tire_radius=.53f;c.spring_rate=25500;c.ride_height=.45f;c.suspension_travel=.3f;c.tire_pressure=.65f;c.tire_grip=1.3f;c.final_drive=1.35f;return c;}
int main(){int failures=0;auto test=[&](const char*n,auto f){try{f();std::cout<<"PASS "<<n<<"\n";}catch(std::exception&e){++failures;std::cerr<<"FAIL "<<n<<": "<<e.what()<<"\n";}};
 test("elevated rock-only support drives and brakes",[]{SoftRig r;r.set_terrain(3);r.set_test_rocks({crawl_rock(0,0,12,60,2)});r.reset({0,3.4f,15});run(r,4,0,true);float total=0;for(int w=0;w<4;++w){total+=r.wheel_rock_load(w);check(r.particles[r.wheel_hubs[w]].pos.y-r.config().tire_radius>1.8f,"hidden ground support");}check(total>r.config().mass*8&&total<r.config().mass*11,"rock load does not support weight");auto p=r.center();run(r,3,.15f);float distance=p.z-r.center().z;std::cout<<"  travel="<<distance<<" speed="<<r.speed()<<" rock_load="<<total<<"\n";check(distance>1&&distance<8,"rock traction or gearing");run(r,2,0,true);check(r.speed()<.03f,"rock brake failed");healthy(r);});
 test("incline hold release and restart",[]{SoftRig r;r.configure(crawler());r.set_terrain(3);r.set_test_rocks({crawl_rock(0,0,14,24,3,.22f)});r.reset({0,4.4f,0});run(r,4,0,true);auto p=r.center();run(r,6,0,true);std::cout<<"  incline drift="<<(r.center()-p).length()<<" speed="<<r.speed()<<"\n";check((r.center()-p).length()<.025f,"hill hold creep");run(r,4,.3f);check(p.z-r.center().z>1,"incline restart failed");healthy(r);});
 test("beveled ledge climb at controlled throttle",[]{SoftRig r;r.configure(crawler());r.set_terrain(3);r.set_test_rocks({crawl_rock(0,-2,8,8,.30f)});r.reset({0,1.5f,5});run(r,3,0,true);float max_vy=0;for(int i=0;i<1440;++i){r.step(1.f/120,.30f,0,false);max_vy=std::max<float>(max_vy,std::abs(r.velocity().y));}std::cout<<"  ledge z="<<r.center().z<<" max_vy="<<max_vy<<"\n";check(r.center().z<-3,"ledge blocked");check(max_vy<2.5f&&r.up().y>.9f,"ledge launched vehicle");healthy(r);});
 test("variable cadence on angular crawl drive",[]{SoftRig a,b;a.configure(crawler());b.configure(crawler());a.set_terrain(3);b.set_terrain(3);run(a,3,0,true,1.f/30);run(b,3,0,true,1.f/120);run(a,8,.22f,false,1.f/30);run(b,8,.22f,false,1.f/120);check((a.center()-b.center()).length()<.015f,"frame dependent crawl");healthy(a);healthy(b);});
 test("airborne tire torque does not move chassis horizontally",[]{SoftRig r;r.set_terrain(3);r.reset({0,40,0});run(r,1,.5f);check(std::abs(r.center().z)<.01f,"air drive injected chassis momentum");check(std::abs(r.wheel_angular_velocity(0))>1,"air tire not spinning");healthy(r);});
 test("shared convex rock faces point outward",[]{for(auto&r:crawl_course())for(auto t:r.triangles){auto a=r.vertices[t[0]],b=r.vertices[t[1]],c=r.vertices[t[2]],n=(b-a).cross(c-a).normalized();for(auto v:r.vertices)check((v-a).dot(n)<.001f,"nonconvex collision piece");} });
 test("split-grip axle lock changes available drive",[]{
 auto distance=[](bool locked){SoftRig r;Config c;c.locked_diffs=locked;r.configure(c);r.set_terrain(3);auto left=crawl_rock(-1.6f,0,3.2f,60,2);left.surface=.035f;auto right=crawl_rock(1.6f,0,3.2f,60,2);r.set_test_rocks({left,right});r.reset({0,3.4f,12});run(r,4,0,true);auto start=r.center();run(r,2,.2f);healthy(r);return start.z-r.center().z;};
 float open=distance(false),locked=distance(true);std::cout<<"  split grip open="<<open<<" locked="<<locked<<"\n";check(locked>open*1.6f&&locked>1,"locker has no causal split-grip advantage");});
 test("skid high-centering unloads tires",[]{SoftRig r;r.set_terrain(3);r.set_test_rocks({crawl_rock(0,0,1.25f,1.8f,1.4f)});r.reset({0,2,0});run(r,5,0,true);float load=0;for(int w=0;w<4;++w)load+=r.wheel_load(w);SoftRig coast=r;auto start=r.center();run(r,2,.2f);run(coast,2,0);std::cout<<"  high center wheel load="<<load<<" movement="<<(r.center()-start).length()<<"\n";check(load<r.config().mass&& (r.center()-coast.center()).length()<.03f,"belly support failed to unload drive");healthy(r);});
 test("lower pressure compresses under the same load",[]{auto height=[](float pressure){SoftRig r;Config c;c.tire_pressure=pressure;r.configure(c);r.set_terrain(3);r.set_test_rocks({crawl_rock(0,0,12,30,2)});r.reset({0,3.5f,0});run(r,4,0,true);return r.particles[r.wheel_hubs[0]].pos.y;};float soft=height(.5f),firm=height(1.5f);std::cout<<"  pressure clearance cost="<<firm-soft<<"\n";check(firm-soft>.006f&&firm-soft<.08f,"pressure has no load-compliance tradeoff");});
 test("complete Copperline course with actual controls",[]{SoftRig r;r.configure(crawler());r.set_terrain(3);run(r,3,0,true);float min_up=1;for(int i=0;i<120*70;++i){float steer=std::clamp<float>(-r.center().x*.7f-r.forward().x*2,-.6f,.6f);bool stop=r.center().z<-78;r.step(1.f/120,stop?0:.30f,steer,stop);min_up=std::min<float>(min_up,r.up().y);}std::cout<<"  course finish z="<<r.center().z<<" min_up="<<min_up<<" speed="<<r.speed()<<"\n";check(r.center().z<-78&&r.speed()<.05f&&min_up>.7f,"course not completed controllably");healthy(r);});
 std::cout<<"CRAWLING: 10 scenarios, "<<failures<<" failures\n";return failures?1:0;}
